from marker.converters.pdf import PdfConverter
from marker.models import create_model_dict
from marker.config.parser import ConfigParser

pdf_converter = None

async def init_converter():
    """
    Initialize the global PDF converter with a pre-configured model dictionary.
    
    This asynchronous function sets up the global `pdf_converter` by creating a new PdfConverter instance
    using a model dictionary generated by `create_model_dict()`. It prints a status message during initialization.
    
    Note:
        - Modifies the global `pdf_converter` variable
        - Should be called before attempting to use the PDF converter
    """
    global pdf_converter
    print("Initializing PDFConverter...")
    pdf_converter = PdfConverter(artifact_dict=create_model_dict())

def get_converter():
    """
    Retrieve the current PDF converter instance.
    
    Returns:
        PdfConverter or None: The global PDF converter instance, or None if not initialized.
    """
    return pdf_converter

