
"""delete content column to PDFDocument

Revision ID: b0db955f32e5
Revises: a1366f80ea44
Create Date: 2025-01-11 11:53:06.917374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0db955f32e5'
down_revision: Union[str, None] = 'a1366f80ea44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pdfdocument', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('pdfdocument', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfdocument', sa.Column('content', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.alter_column('pdfdocument', 'file_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
