"""update pdfdoc to latest sepcs

Revision ID: b4702dbd669d
Revises: b0db955f32e5
Create Date: 2025-01-12 15:18:09.699137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4702dbd669d'
down_revision: Union[str, None] = 'b0db955f32e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfdocument', sa.Column('file_content', sa.TEXT(), nullable=True))
    op.drop_column('pdfdocument', 'description')
    op.drop_column('pdfdocument', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pdfdocument', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pdfdocument', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('pdfdocument', 'file_content')
    # ### end Alembic commands ###
