"""update pdfdoc to latest sepcs

Revision ID: b4702dbd669d
Revises: b0db955f32e5
Create Date: 2025-01-12 15:18:09.699137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4702dbd669d'
down_revision: Union[str, None] = 'b0db955f32e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Applies database schema migration to update the `pdfdocument` table.
    
    Performs the following schema changes:
    - Adds a new `file_content` column of type TEXT (nullable)
    - Removes the `description` column
    - Removes the `file_path` column
    
    This is an Alembic upgrade migration function that modifies the database structure.
    
    Notes:
        - Executed during database migration process
        - Irreversible changes to table structure
    """
    op.add_column('pdfdocument', sa.Column('file_content', sa.TEXT(), nullable=True))
    op.drop_column('pdfdocument', 'description')
    op.drop_column('pdfdocument', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Reverts the previous database migration by restoring the `file_path` and `description` columns to the `pdfdocument` table and removing the `file_content` column.
    
    This function is part of an Alembic migration script that rolls back schema changes to the `pdfdocument` table. It performs the following operations:
    - Adds back the `file_path` column as a non-nullable VARCHAR
    - Adds back the `description` column as a nullable VARCHAR with a maximum length of 500
    - Drops the `file_content` column from the table
    
    Raises:
        SQLAlchemy exceptions may be raised during column manipulation if database constraints are violated
    
    Note:
        This is a database migration downgrade method used to revert schema changes.
    """
    op.add_column('pdfdocument', sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('pdfdocument', sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('pdfdocument', 'file_content')
    # ### end Alembic commands ###
