name: Docker Compose CI/CD

on:
  push:
    branches: [ "main", "Phase1", "Phase1.1" ]
  pull_request:
    branches: [ "main", "Phase1", "Phase1.1" ]

jobs:

  docker-compose:

    runs-on: ubuntu-latest

    # Step 0: Free Space
    steps:
    - name: Free up disk space
      run: |
        sudo apt-get clean
        sudo rm -rf /usr/local/lib/android /opt/ghc /usr/share/dotnet
        docker system prune -a -f

    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set Up Docker Environment
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build and Start Services with Docker Compose
    - name: Build and Run Services
      run: docker compose up --build -d

   # Step 4: Tear Down the Services
    - name: Tear Down Services
      run: docker compose down

