name: Docker Compose CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-compose:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v4

    # Step 2: Set Up Docker Environment
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Build and Start Services with Docker Compose
    - name: Build and Run Services
      run: docker compose up --build -d

   # Step 4: Tear Down the Services
    - name: Tear Down Services
      run: docker compose down

